name: Build and Deploy to SiteGround

on:
  push:
    branches: [ "master" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SG_HOST }}
          username: ${{ secrets.SG_USER }}
          password: ${{ secrets.SG_PASS }}
          protocol: ftps
          local-dir: ./out/   # Next.js static export directory
          server-dir: public_html/ # SiteGround document root
